version: '3.8'

services:
  webapi:
    container_name: crawlerwebapi_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7056:7056"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=3306;Database=mydatabase;Username=root;Password=root;"
    depends_on:
      - db

  frontend:
    container_name: crawlerreact_container
    build:
      context: ./WebCrawlerApp.API/frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
